### ISSUE TITLE
Toggling outline view makes right margin shift left

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#6] opened 2019-03-01 14:07 UTC
Triggering the outline view closed causes the main window's right edge to shift too far to the left. Doing this multiple times causes the right margin to continue to grow. This is most obvious in full screen mode, but happens in normal mode as well.

**Comment by lmparppei** [comment] 2019-03-01 15:48
Could you send a screenshot? 
Does it happen in the latest release?
https://www.dropbox.com/s/g51ew1npdps5r68/Beat%201.0.4b.zip?dl=1

**Comment by darthrootbeer** [comment] 2019-03-01 16:40
Was on the last version of 1.0.3 when I tested, but yes -- still happening in Version 1.0.5 (362).

Standby.

**Comment by lmparppei** [comment] 2019-03-01 16:43
Oh yeah, could no reproduce. This is VERY strange.

**Comment by darthrootbeer** [comment] 2019-03-01 16:45
I thought it was related to the issue where scene numbers also shift left when toggling bookmarks. Maybe. I'll leave you to your alchemy.

**Comment by lmparppei** [comment] 2019-03-01 17:22
The problem was that toggling outline wasn't aware the app was in full screen, so it tried to resize the whole window which made it expand  over the screen bounds.

Fixed in 1.0.5b.

**Closed by lmparppei** 2019-03-01 17:22 UTC
