### ISSUE TITLE
So many problems now

### ISSUE THREAD

**Issue by keith105** [lmparppei/Beat#162] opened 2024-08-31 18:28 UTC
I've been using this software for quite a while. Suddenly, it seems completely riddled with bugs.

1. Most of the scene transitions (e.g. "DISSOLVE TO:") are showing up left justified. The only way to fix them is to completely delete the line and create a new one.
2. When I type the name of a character and enter return, the cursor moves to the BEGINNING of the next line rather than more towards the center where the dialog belongs.
3. I started adding text to the end of the first description line of a scene and suddenly all of the text on that line became capitalized.
4. I quit the Beat app and start it up again, and now all of the page numbers are all wrong! Multiple page 6s, etc, etc, etc.

This is happening to me at the absolute WORST TIME. I have until midnight tonight to complete my screenplay to submit it to the ScreenCraft Drama competition. I do not have time to deal with this.

**Comment by lmparppei** [comment] 2024-08-31 19:21
Please follow the instructions to reporting bugs (Beat version, computer model, macOS or iOS version) and also provide minimal example files which reproduce these issues.

Could you also clarify a bit:

- do the transition lines show up correctly if you close the file (after a wrongly parsed line type) and reopen it?
- do you have *Hide Fountain markup* on?
- if possible, create a screen recording of the character cue issue

Thank you!

**Comment by lmparppei** [comment] 2024-09-01 13:33
I made some time to try and reproduce some of these problems myself, but I can't find a way to make them appear.

I'm presuming there's something in that specific file that Beat isn't able to parse – wrong page numbers, weird scene heading issues and parsing problems hint towards a parsing issue or a disconnect between the editor and parser. If you can, please send the file to beat@beat-app.fi. I **will not** look into the contents and I'll delete the file right away, I'll just run it through the parser code to see what could be causing the possible disconnect.

> 1. Most of the scene transitions (e.g. "DISSOLVE TO:") are showing up left justified. The only way to fix them is to completely delete the line and create a new one.

I can't reproduce this in any document in Beat 1.999.20. Please give me exact details or a simple file to show the issue.

> 2. When I type the name of a character and enter return, the cursor moves to the BEGINNING of the next line rather than more towards the center where the dialog belongs.

This is a graphical glitch in macOS TextKit which was fixed for a while and now broken again, and I've submitted a bug report to Apple. It happens only when writing dialogue at the end of the document.

> 3. I started adding text to the end of the first description line of a scene and suddenly all of the text on that line became capitalized.

Again, can't reproduce this in any version of Beat. 

> 4. I quit the Beat app and start it up again, and now all of the page numbers are all wrong! Multiple page 6s, etc, etc, etc.

Please clarify: Does this happen in **editor** or in **export** or **preview**?

**Comment by keith105** [comment] 2024-09-01 22:15
It happens in editor. And I also found it was mangling my text. I'd edit text somewhere, and later when I'd return to that page, some of the characters were either deleted or replaced by other random characters, often not even alphabetical characters.

This problem became so bad I had to use a different editor. I bought Fade In. Thankfully I managed to get my changes done just in time and submitted 45 minutes before the deadline.

**Comment by lmparppei** [comment] 2024-09-02 06:00
> I'd edit text somewhere, and later when I'd return to that page, some of the characters were either deleted or replaced by other random characters, often not even alphabetical characters.

This sounds like a glyph layout issue. Beat didn't mangle your text, it just got displayed incorrectly. Similar problems have been reported on Intel Macs, but they were usually fixed with a restart / reinstall. No idea why, but even Apple's own TextEdit is affected by this, so it hints to a deeper issue in macOS.

**Comment by keith105** [comment] 2024-09-03 23:15
It's definitely not just a display issue. I had the file converted into Final Draft format and imported it into Fade In app, and it was displaying the same way there too. I edited it there and the problems went away.

All of the problems seem to happen on the line just before or after a title. On transition lines and first action lines. And it was only happening to text that I had recently edited.

**Comment by lmparppei** [comment] 2024-09-04 17:39
Beat will not change any characters or content unless you tell it to, but there might be a disconnect between the editor and parser.

Did this happen in _any_ file, or just this one? Could you give me a screenshot of what happened? I know you are a Fade In user now, but this is a pretty esoteric problem which can't be reproduced on the computers I have tried it on, so any help to resolve this would be greatly appreciated :-)

**Comment by lmparppei** [comment] 2024-12-03 19:21
No further reports about this have arrived, I guess this is either resolved or forgotten.

**Closed by lmparppei** 2024-12-03 19:21 UTC
