### ISSUE TITLE
Find and Replace bar gets cut off after being activated.

### ISSUE THREAD

**Issue by BFLTP** [lmparppei/Beat#99] opened 2022-01-13 17:47 UTC
As shown in the below image, most of the Replace portion of the Find and Replace bar disappears several seconds after being activated by the checkbox. All the Find and Replace functions still work normally in this condition, but clicking where the input field and the buttons would be does not work. Unchecking and rechecking the box makes the bar appear normally again, but it disappears on its own again after a brief time. Opening Find and Replace directly with the Edit menu button or with the keyboard shortcut does not make it appear normally again.

![](https://user-images.githubusercontent.com/58162030/149380968-5ee6826c-bcb8-4d1d-bc53-435a31ed632e.png)

This is how it should appear normally:

![](https://user-images.githubusercontent.com/58162030/149381719-7a8a46ae-fc28-4ed3-b777-d5a2e223d53d.png)

**Comment by lmparppei** [comment] 2022-01-13 18:25
I can't reproduce this. On which macOS are you? Could you maybe capture a video of the issue?

Also, does the bar change height at the same time when the top icons disappear?

**Comment by lmparppei** [comment] 2022-01-13 18:53
I might have fixed this. The bug is not present in Big Sur (which I'm still on for software compatibility), but I found an old method related to the unified title bar look, which probably caused this.

**Comment by BFLTP** [comment] 2022-01-14 00:54
> Also, does the bar change height at the same time when the top icons disappear?

No, the Find and Replace bar does not change like this when the top icons disappear. (The top icons disappear because of mouse inactivity, correct?)

> I might have fixed this. The bug is not present in Big Sur (which I'm still on for software compatibility), but I found an old method related to the unified title bar look, which probably caused this.

If you’d like to send me one, I’d be happy to try a development build and check whether that change fixed the issue.

**Comment by ftolsson** [comment] 2022-02-02 08:50
FYI, I'm wondering if this is not a screen size issue rather than an OS issue.

I get the below (still on Big Sur) but not on my laptop, only on my external monitor (3840x2160)

It simply seems as if the overlay obscures too much of the screen (measurements seem the same for both cases, although mine is still see-through). The problem occurs both if the app launched with this monitor attached OR if launched on the laptop screen first and then hooked up to monitor.

Finally, for me it corrects itself if I scroll the page at all. So it's really a small cosmetic glitch, at least on Big Sur. 

<img width="961" alt="image" src="https://user-images.githubusercontent.com/25481285/152120911-d6584a97-c46a-4d98-a8c4-4316fbb4c692.png">

**Comment by lmparppei** [comment] 2022-02-02 08:53
I think I know what's causing this, but can't find any traces of that old code anywhere.

**Comment by lmparppei** [comment] 2022-03-17 15:07
I'm now able to reproduce this in Monterey. I'll fix it ASAP.

**Comment by adiffer** [comment] 2022-04-09 04:50
Still happening. I'm on OS 12.3.1 now.

To me it looks like the panel with the find/replace objects gets redrawn when focus shifts to a new thing found in the text editor. I don't think the redrawing method knows that the 'replace' selection has been checked, so it draws the shorter window one would expect around just the 'find' objects. It might not look for the check, or it might be getting a null and assuming.

![BeatBug](https://user-images.githubusercontent.com/2776505/162556857-b1681dc6-8637-4bb9-935d-ccf2451373c4.png)
.

**Comment by lmparppei** [comment] 2022-04-10 08:39
Fixed in `1.94.2`. Caused by not calling `super` method in my `NSScrollView` subclass.

**Closed by lmparppei** 2022-04-10 08:39 UTC
Labels: bug
