### ISSUE TITLE
1.92.2: API doesn't look for content in Sections

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#82] opened 2021-12-01 12:45 UTC
It seems that in the latest version of Beat, `Beat.outline()` always reports every `Section` as having the length of one single line, the content of which is the section's title. Then, nothing more, even if there is indeed content below. 

Practically, this means that for a section with notes, those notes will never be exposed by the API.

This is a change from previous versions where everything between a section and next outline element was content of that section, so here's hoping that's an involuntary change.

Screenshots below, hopefully clarifying what I mean. 

**1. Previous versions**

><img width="868" alt="image" src="https://user-images.githubusercontent.com/25481285/144231791-249d9421-53c3-40ae-8aa6-888c1aac7ca1.png">

**2. Current (1.92.2)**

><img width="863" alt="image" src="https://user-images.githubusercontent.com/25481285/144232454-0e738187-581f-4ad0-9925-03a168780be2.png">

**Comment by lmparppei** [comment] 2021-12-01 12:48
This is caused by restructuring of the outline data. A human mistake, as I forgot that previously section objects could actually contain other stuff as well beside the section title. Easy to fix. Relevant code is found in `OutlineScene.m`, under `- (NSInteger)length` if anybody is interested looking into this before I return to development

**Comment by ftolsson** [comment] 2021-12-01 12:54
I honestly hoped you wouldn't be looking here (and that you'd turned off notifications) until you were back.
Keep winding down and taking care of yourself!

**Comment by lmparppei** [comment] 2021-12-06 11:36
Fixed in `1.92.3`

**Closed by lmparppei** 2021-12-06 11:36 UTC
