### ISSUE TITLE
Adjusting font size quickly takes a long time and can cause app to be unresponsive

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#17] opened 2019-03-01 14:18 UTC
Using (Cmd - or Cmd + ) a few times quickly takes a long time. Can cause a spinning beach ball. 

Might only happen with larger files. 

One solution would be to resize only what's on-screen first, then handle the rest of the file as a background process.

Sample script: Big Fish.

[BIG FISH [John August] [Final] [Digital].fountain.zip](https://github.com/lmparppei/Beat/files/2919757/BIG.FISH.John.August.Final.Digital.fountain.zip)

**Comment by lmparppei** [comment] 2019-03-01 16:10
Yeah. This is an issue, and the reason is that the whole script is formatted again every time the font size is changed.

There is a solution to this, which is magnifying the NSView, but I have NO IDEA how to control the magnification so that it keeps everything centered. There is some work done on this in the code, but for now this unresponsive and bad implementation is the way to go, unfortunately.

**Comment by darthrootbeer** [comment] 2019-03-01 16:38
Not really a showstopper, because most users will set a font size and then stick with it, I expect.

**Comment by lmparppei** [comment] 2019-04-29 20:09
This is still an issue, unfortunately. I think I need help subclassing the NSTextView component, which is already subclassed to provide the autocomplete feature.

Magnification kinda works when zooming in, but it gets messed up when resizing the window. The page insets are created by the following calculation:

`(textView width / 2) - (zoom level * unit)`

The latter part returns the page width. Well, obviously this won't work with magnification, because the NSTextView width won't help us when the window is resized. Basically we would need a NSTextView where the view keeps the TextContainer centered even when resize.

This is the *biggest issue* with Beat right now, so if anyone can help or could direct me to some easily zooming and content-width-retaining NSTextView subclass, I'd be super thankful.

**Comment by walsh2000** [comment] 2019-05-07 02:57
I just checked out the app and cannot reproduce the beachballing issue on a "MacBook Pro (Retina, 15-inch, Late 2013)" running 10.14.4
Are the steps to reproduce the spinning more than Cmd-Plus, Cmd-Plus, Cmd-Plus, Cmd-Plus ?

Are we using this issue to track the not-quite-centered or the spinning?

**Comment by lmparppei** [comment] 2019-05-07 08:18
The unresponsiveness was fixed yesterday (forgot to update this thread), but the centering can still cause. some trouble.

Zoom in / out code is a mess right now, I need to go through it and clean it up when I can. Maybe I will open up a new issue for the whole thing.

**Comment by lmparppei** [comment] 2019-09-02 12:40
I attempted to fix this, but no luck. I have how to get the magnification to work, and unfortunately have no time to try and fix it. I will return to this issue some day.

**Comment by lmparppei** [comment] 2019-09-06 10:01
This will finally be fixed in version 1.1. My approach uses `scaleUnitSquareToSize`. The approach is a bit shady but seems to work. New zooming will be available in the next release & update!

**Closed by lmparppei** 2019-09-06 10:01 UTC
Labels: bug, help wanted
