### ISSUE TITLE
Some dialogue items (with periods) misinterpreted as sluglines

### ISSUE THREAD

**Issue by darthrootbeer** [lmparppei/Beat#13] opened 2019-03-01 14:13 UTC
Opening a script with ".44" in a dialogue block shows a forced slug instead. Unable to reproduce after first occurrence. Could not recreate with new file, either. 

This occurred when opening the attached fountain file (could be bad format, or just a fountain bug).

[48 HRS [1982] [Fountain] [Spottiswoode, Hill].fountain.zip](https://github.com/lmparppei/Beat/files/2919730/48.HRS.1982.Fountain.Spottiswoode.Hill.fountain.zip)

**Comment by lmparppei** [comment] 2019-03-01 16:15
Well, that might happen. Starting a line with . forces a scene heading in Fountain, so you should escape it with escape character (\.). Not ideal for newcomers, but mostly seems to work as intended for compatibility.

**Comment by lmparppei** [comment] 2020-01-21 11:54
Fixed in 1.1.0 release.

**Closed by lmparppei** 2020-01-21 11:54 UTC
