### ISSUE TITLE
Bug: Parenthetical Missing From Dialog That is First Line on Page

### ISSUE THREAD

**Issue by emmgunn** [lmparppei/Beat#136] opened 2023-09-10 21:51 UTC
My apologies if this has already been addressed, but I did do a quick search and couldn't find anything related to the following. It appears that if I have dialog on the first line of a page, then if dialog includes a parenthetical, it's missing in print previews and PDF's. 

For example:
<img width="960" alt="image" src="https://github.com/lmparppei/Beat/assets/7763446/3b5290eb-f63d-4842-b6a8-f64b71a1271b">
has this print preview:
<img width="734" alt="image" src="https://github.com/lmparppei/Beat/assets/7763446/7957e4d8-1647-48f0-994c-9e4661bd23e3">

While if I add a line to push the dialog down:
<img width="953" alt="image" src="https://github.com/lmparppei/Beat/assets/7763446/8d94c3f2-eaaf-4b76-b714-cd572bacb229">

I get as expected:
<img width="728" alt="image" src="https://github.com/lmparppei/Beat/assets/7763446/a9a2c3b0-e13d-4618-97b1-9e7d5035eac4">

I'm on a MacBook Pro running Ventura 13.5. Thanks!

**Comment by lmparppei** [comment] 2023-09-10 21:55
I can't reproduce this myself. Could you attach a document which displays this behavior?

Also, are you on the latest version of Beat? (1.99.67)

**Comment by lmparppei** [comment] 2023-09-10 21:56
No, disregard that – I actually can! I'll work out a fix. Thank you for reporting.

**Comment by lmparppei** [comment] 2023-09-10 22:09
Fixed in **1.99.68**

**Closed by lmparppei** 2023-09-10 22:09 UTC
Labels: bug

**Comment by emmgunn** [comment] 2023-09-11 00:02
Thanks for the quick turnaround on the bug! Have a great day.
