### ISSUE TITLE
Forced scene number makes Beat incorrectly parse scene color tag when printing/previewing

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#68] opened 2021-09-28 08:27 UTC
**Insight:** A great way to override Fountains agnosticism towards SHOT elements is to add a forced scene heading and giving it a forced non-number (space) like so:

```
EXT. A LARGE FIELD -- DAY [[COLOR YELLOW]]

Person A does something in the middle of the field

.AT A DISTANCE # # [[COLOR BLUE]]

Person B is hiding in shrubbery, watching A through binoculars

.IN THE MIDDLE OF THE FIELD # # [[COLOR YELLOW]]

Person A keeps doing that something
```

**Result:** The shots appear in the outline (or my plugin for that matter :) but are not numbered, thus not increasing scene numbers until next *actual* scene (while still allowing me to clearly color code which cut belongs to which character). Great stuff! 

**Problem:** This being an edge case if there ever was one, the printout will not correctly parse those lines. Instead, they will print like this: 

```
AT A DISTANCE  [C
```

Actually, this holds true for any locked scene number (even the expected ones with only numbers or number + letter) where the color comment is partly not stripped from the printout.

**Comment by lmparppei** [comment] 2021-09-28 16:55
This is caused by screenplay preprocessing for printing. I'll fix it in `1.90.1` before release.

**Comment by lmparppei** [comment] 2021-09-29 10:10
Fixed in `1.90.1` and added correct scene number formatting ranges to `- (NSIndexSet*)formattingRanges` in `Line.m`

**Closed by lmparppei** 2021-09-29 10:10 UTC

**Comment by ftolsson** [comment] 2021-09-29 10:11
Hope you didn't disallow empty numbers! 😊 
It really is a great workaround for shots!

**Comment by lmparppei** [comment] 2021-09-29 13:12
It still works, and it's actually a very clever trick. I could add a menu item for doing that, like *Remove Scene Number*.

**Comment by lmparppei** [comment] 2021-09-29 14:25
Off-topic, but I've added two new menu items:
- *Make Scene Non-Numbered*
- *Set Scene Number For Current Scene*
