### ISSUE TITLE
1.925: getDocumentSetting (and its Raw equivalent) crashes Beat

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#92] opened 2021-12-28 09:53 UTC
At the risk of this being me, not you — trying to do this...

```
Beat.setDocumentSetting("Hello", "World")
let value = Beat.getDocumentSetting("Hello")
```

...will make Beat crash. (the `set` part works fine, it's the `get` that doesn't). 
This is what the console.app tells me:

```
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: 
'[<BeatDocumentSettings 0x600000885780> valueForUndefinedKey:]: 
this class is not key value coding-compliant for the key FTOutliner: Hello.'
```

I *think* I'm doing it the way you tell me in the wiki — Raw is for accessing your built-in, app-generated settings, correct? — but I'm thinking even if I'm wrong a crash is probably not the desired result...

Hope you had a great Christmas!

**Comment by lmparppei** [comment] 2021-12-28 19:04
I have failed once again. I'll fix it.

**Comment by ftolsson** [comment] 2021-12-28 19:08
You have not failed, you have successfully ruled out yet another way to implement it.

**Comment by lmparppei** [comment] 2021-12-29 11:54
I just completely mistyped the method. This is **FINALLY AND ACTUALLY** fixed in `1.92.6`. Won't close the issue until these calls are verified to be working.

**Comment by ftolsson** [comment] 2021-12-29 12:10
Do! Dare to close it! 
I'll keeping being that guy who types into closed threads!*

*In case it isn't finally and actually fixed, that is. Which of course it is!

**Comment by lmparppei** [comment] 2021-12-29 20:02
This time I actually TESTED it myself, and everything seems to work as intended.

```javascript
Beat.setDocumentSetting("Hello", "Earth")
let setting = Beat.getDocumentSetting("Hello") // Returns "Earth"

let pageSize = Beat.getRawDocumentSetting("Page Size") // Returns either 0 or 1

```

**Closed by lmparppei** 2021-12-29 20:02 UTC
