### ISSUE TITLE
Emphasis malfunctions if it is in a forced action line preceded by another action line.

### ISSUE THREAD

**Issue by BFLTP** [lmparppei/Beat#83] opened 2021-12-03 16:39 UTC
If a forced action line is preceded by another action line, any emphasis in the forced action line does not render properly. For example,
![](https://user-images.githubusercontent.com/58162030/144636302-36c7d2c4-ad7f-4827-8b87-5d06c28b375b.png)
![](https://user-images.githubusercontent.com/58162030/144636601-63b65b56-5082-491c-994f-7aa5ddb6685f.png)
![](https://user-images.githubusercontent.com/58162030/144636627-35368144-8c58-41d1-8bcf-3dda89fd5995.png)
![](https://user-images.githubusercontent.com/58162030/144636657-65cad15b-0af6-447e-abe0-7836b338ecfd.png)

From [this message in the Beat Discord server](https://discord.com/channels/717443575750852759/764599676959719464/915869751727751219).

This issue does not occur with regular action lines.

While forcing the action line in the example above is not necessary, one case in which this bug becomes a practical issue is the following:
```
He reads the Twitter handle again...
!@melonhusk was *Elon Musk's* account!
```
Without the `!`, `@melonhusk was *Elon Musk's* account!` would be interpreted as a transition. This bug causes the italicized `Elon Musk's` to be rendered improperly.

Let me know if there are any other example cases you would like me to include in this record.

**Comment by lmparppei** [comment] 2021-12-06 11:35
This was caused by joining preceding action lines into single paragraphs. Force symbol was ignored correctly (`!`), but it messed up other markup ranges. Fixed in `1.92.3`

**Closed by lmparppei** 2021-12-06 11:35 UTC
