### ISSUE TITLE
Very small issue: Must >centered text< have a blank line above (or not)?

### ISSUE THREAD

**Issue by ftolsson** [lmparppei/Beat#125] opened 2022-09-02 11:17 UTC
Let's say I want a couple of centered paragraphs. 
They work fine in the editor:
<img width="621" alt="image" src="https://user-images.githubusercontent.com/25481285/188127700-42e33d40-de7c-4c3a-9292-88d66c19577e.png">

But in print and preview, they cannot be made to appear on adjacent lines:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/25481285/188127668-426e3e75-0fd2-4a50-a444-5bb592aea51e.png">

I'm thinking that if nothing else, the editor should then probably force that line too so that the print doesn't come out as a surprise.
(But my vote would be on not adding a blank line above centered text -- not least to be able to stack stuff like above.)

That's all, hope you agree!

**Comment by lmparppei** [comment] 2022-09-02 11:31
This is actually not a *small* issue, because I've struggled with it quite a lot. The issue is caused by the significance of whitespace when parsing Fountain markup. I think the quickest fix would be to just join consecutive centered lines into one paragraph.

The issue itself:
• Empty lines are completely ignored by default and whitespace is created when rendering the document
• If you have two action lines with no whitespace between them, Beat merges those lines into the earlier one while preprocessing parsed contents for rendering. To preserve stylization, formatted indices in the later line are copied into the preceding one. This works pretty well, though I'm sometimes still fixing bugs dealing with merging lines.
• **HOWEVER**: A centered line is a line type, not a formatting choice. The quickest fix for this would be to apply the same logic as with action lines, and just merge the centered lines into one paragraph. It should work well with your example.
• If somebody would want to have a centered line in between of a paragraph, the current system makes it very tricky. The `Line` object should contain something like `centeredIndices`, and Beat would wrap those ranges into containers that are displayed as `block`s. I'm a bit scared to do that, honestly.

For now, I think I'll just settle to merging neighboring centered lines.

**Comment by ftolsson** [comment] 2022-09-02 11:45
Well, nobody in their right mind should do this anyway, it's just ugly:  :)
<img width="566" alt="image" src="https://user-images.githubusercontent.com/25481285/188131527-3c252dd9-0199-4eb1-b898-016c8ca527be.png">

Seriously though -- sorry for implying it'd be simple (though I did mean it was trivial problem to live with for me as a user, not trivial to fix).

Just a question about the third bullet point, that a centered line is a line type -- isn't that a good thing in itself though?
Wouldn't that help you (disregarding blank lines, as you say) to just acknowledge the `>` in the beginning, regardless of preceding blank line or not? 
And then, at render time, add a blank line above,`if (previousLine.typeAsString() != "Centered")`. 

Perhaps that's just as hard/easy as your own suggestion, I'm just thinking it makes more sense to keep the paragraphs apart if that's how they were entered... But I admit I might be overthinking it, it's just about to take physical form so as long as it looks correct I guess maintaining types etc is less important.

**Comment by lmparppei** [comment] 2022-09-02 12:33
Blank lines are not added, but created using element margins. The lines are merged when preprocessing the parsed content for exporting. This is not a difficult thing *per se*, I might have overthought it originally when I tried to implement mid-paragraph centering.

**Comment by lmparppei** [comment] 2022-09-02 13:29
Editor:
![image](https://user-images.githubusercontent.com/20226704/188156226-19ae3606-4de7-4769-a33a-8955e12e2c9e.png)
Rendered:
![image](https://user-images.githubusercontent.com/20226704/188156333-7d1589a0-ae24-49fa-80ca-36c432121c6f.png)

I had to take the cue from lyric blocks, rather than paragraphs. I'm a bit worried about how this is taken into account in pagination, but let's see.

**Comment by lmparppei** [comment] 2022-09-02 13:50
... yeah, it required some tweaking and revealed more underlying issues in my code, but they've been fixed now. It's Friday and I didn't get any writing done, but sometimes that's OK.

**Closed by lmparppei** 2022-09-02 13:50 UTC
Labels: bug

**Comment by ftolsson** [comment] 2022-09-02 18:45
I hear you. I'm thinking next week's me will surely be a lot more productive than me of this week.
(And probably a bit angry that I left him so much, but that's exactly how I felt when this week started too.)

Great job as always! Enjoy your weekend.
